# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:            kramdown
highlighter:         true

# Setup
title:               Jeffrey De Fauw
tagline:             'Machine Learning research'
description:         'Jeffrey De Fauw'
url:                 https://jeffreydf.github.io
baseurl:             ''
paginate:            5


# About/contact
author:
  name:              Jeffrey De Fauw
  url:               https://twitter.com/JeffreyDeFauw
  email:             jeffrey@mathbb.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
